# Generated by Django 2.1.7 on 2019-03-16 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RwwaHorse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horseNumber', models.IntegerField()),
                ('horseName', models.CharField(max_length=60)),
                ('horseBarrier', models.IntegerField()),
                ('horseRider', models.CharField(max_length=60)),
                ('horseTrainer', models.CharField(max_length=60)),
                ('horseOdds', models.CharField(max_length=10)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RwwaRace')),
            ],
        ),
    ]
